import { PersonaConfig, UserPersona } from '../types/persona';

export const PERSONA_CONFIGS: Record<UserPersona, PersonaConfig> = {
  ISRO_ANALYST: {
    id: 'ISRO_ANALYST',
    name: 'ISRO / SPACE ANALYST',
    shortName: 'ISRO Space Analyst',
    icon: 'Satellite',
    badgeColor: 'border-cyan-500/40 bg-cyan-950/60 text-cyan-400',
    accentColor: '#06B6D4',
    description:
      'High-resolution multi-spectral, C-SAR radar analysis, automated object detection, and planetary change monitoring.',
    permissions: {
      canDetectInfrastructure: true,
      canAccessSAR: true,
      canViewEmergencyLayers: true,
      canRunChangeDetection: true,
      canRunSpectral: true,
      canExportOperationalReports: true,
      canExportGeoTIFF: true,
      maxExportLevel: 'OPERATIONAL',
    },
    preferredLayers: ['satellite', 'detections', 'change', 'ndvi', 'bhuvanLulc'],
    quickPrompts: [
      'Count all cargo ships in this harbor',
      'Detect infrastructure in this region',
      'Show urban expansion between 2023 and 2025',
      'Analyze SAR radar backscatter',
      'Calculate NDVI vegetation health',
      'Run multi-spectral reflectance analysis',
    ],
    capabilities: [
      'Optical & SAR Fusion Analysis',
      'YOLOv8-OBB Vessel & Tank Detection',
      'Multi-Temporal Land Use Differencing',
      'ISRO Bhuvan LULC & Geomorphology Layers',
      'Operational Raw Vector & GeoTIFF Export',
    ],
  },

  NDRF_OFFICER: {
    id: 'NDRF_OFFICER',
    name: 'NDRF / DISASTER OFFICER',
    shortName: 'NDRF Disaster Officer',
    icon: 'ShieldAlert',
    badgeColor: 'border-amber-500/40 bg-amber-950/60 text-amber-400',
    accentColor: '#F59E0B',
    description:
      'Rapid flood inundation modeling, SAR water extent mapping, emergency zone evacuation planning, and disaster impact summaries.',
    permissions: {
      canDetectInfrastructure: false,
      canAccessSAR: true,
      canViewEmergencyLayers: true,
      canRunChangeDetection: true,
      canRunSpectral: true,
      canExportOperationalReports: true,
      canExportGeoTIFF: false,
      maxExportLevel: 'OPERATIONAL',
    },
    preferredLayers: ['satellite', 'flood', 'ndwi', 'change', 'bhuvanFlood'],
    quickPrompts: [
      'Highlight flooded areas',
      'Calculate inundation extent',
      'Compare before and after flood',
      'Find affected settlement zones',
      'Show water expansion and river overflow',
      'Generate disaster impact summary report',
    ],
    capabilities: [
      'Sentinel-1 SAR Inundation Thresholding',
      'Submerged Infrastructure Identification',
      'Before vs After Flood Inundation Slider',
      'ISRO Bhuvan Flood Hazard Overlay',
      'Operational Disaster Impact Report Generation',
    ],
  },

  PUBLIC_RESEARCHER: {
    id: 'PUBLIC_RESEARCHER',
    name: 'PUBLIC / RESEARCH USER',
    shortName: 'Public Research User',
    icon: 'GraduationCap',
    badgeColor: 'border-emerald-500/40 bg-emerald-950/60 text-emerald-400',
    accentColor: '#10B981',
    description:
      'Open-access Earth observation, Sentinel-2 vegetation health (NDVI), surface water indices (NDWI), and public GIS research.',
    permissions: {
      canDetectInfrastructure: false,
      canAccessSAR: false,
      canViewEmergencyLayers: false,
      canRunChangeDetection: true,
      canRunSpectral: true,
      canExportOperationalReports: false,
      canExportGeoTIFF: false,
      maxExportLevel: 'PUBLIC',
    },
    preferredLayers: ['satellite', 'ndvi', 'ndwi', 'bhuvanWasteland'],
    quickPrompts: [
      'Calculate vegetation health',
      'Find water bodies',
      'Analyze mangrove vitality in Sundarbans',
      'Compare land cover between 2022 and 2026',
      'Explore Sentinel-2 optical imagery',
      'Export GeoJSON research data',
    ],
    capabilities: [
      'Sentinel-2 Open Optical Reflectance',
      'Normalized Difference Vegetation Index (NDVI)',
      'Normalized Difference Water Index (NDWI)',
      'General Terrain Segmentation',
      'Standard GeoJSON / CSV Research Export',
    ],
  },
};
